language: node_js
node_js:
    - stable
env:
    - CREATE='createUTF8' LARGE_PREFIX='false' ROW_FORMAT='dynamic'
    - CREATE='createUTF8' LARGE_PREFIX='true' ROW_FORMAT='dynamic'
    - CREATE='createUTF8' LARGE_PREFIX='false' ROW_FORMAT='compact'
    - CREATE='createUTF8' LARGE_PREFIX='true' ROW_FORMAT='compact'
    - CREATE='createUTF8mb4' LARGE_PREFIX='false' ROW_FORMAT='dynamic'
    - CREATE='createUTF8mb4' LARGE_PREFIX='true' ROW_FORMAT='dynamic'
    - CREATE='createUTF8mb4' LARGE_PREFIX='false' ROW_FORMAT='compact'
    - CREATE='createUTF8mb4' LARGE_PREFIX='true' ROW_FORMAT='compact'
    - CREATE='createMetaKeyNotMB4' LARGE_PREFIX='false' ROW_FORMAT='dynamic'
    - CREATE='createMetaKeyNotMB4' LARGE_PREFIX='true' ROW_FORMAT='dynamic'
    - CREATE='createMetaKeyNotMB4' LARGE_PREFIX='false' ROW_FORMAT='compact'
    - CREATE='createMetaKeyNotMB4' LARGE_PREFIX='true' ROW_FORMAT='compact'
    - CREATE='createMetaKeyNotMB4IndexWith191' LARGE_PREFIX='true' ROW_FORMAT='dynamic'
    - CREATE='createMetaKeyNotMB4IndexWith191' LARGE_PREFIX='false' ROW_FORMAT='dynamic'
    - CREATE='createMetaKeyNotMB4IndexWith191' LARGE_PREFIX='true' ROW_FORMAT='compact'
    - CREATE='createMetaKeyNotMB4IndexWith191' LARGE_PREFIX='false' ROW_FORMAT='compact'
    - CREATE='createUTF8mb4innodb_large_prefix' LARGE_PREFIX='true' ROW_FORMAT='dynamic'
    - CREATE='createUTF8mb4innodb_large_prefix' LARGE_PREFIX='false' ROW_FORMAT='dynamic'
    - CREATE='createUTF8mb4innodb_large_prefix' LARGE_PREFIX='true' ROW_FORMAT='compact'
    - CREATE='createUTF8mb4innodb_large_prefix' LARGE_PREFIX='false' ROW_FORMAT='compact'
before_install:
    - sudo apt-get install -y pv
before_script:
    - node index.js > sql/import.sql
script:
    - cat sql/$CREATE.sql
    - mysql -e 'CREATE DATABASE app;'
    - |
        if [ "$LARGE_PREFIX" = "true" ]
        then
            sudo cp mysql-custom-innodb_large_prefix.cnf /etc/mysql/conf.d/mysql-custom.cnf
            sudo service mysql restart
        fi
    - mysql < sql/$CREATE.sql
    - |
        if [ "$ROW_FORMAT" = 'dynamic' ]
        then
            mysql < sql/rowFormatDynamic.sql
        fi
    - pv sql/import.sql | mysql app
    - mysql < sql/oldQuery.sql
    - mysql < sql/newQuery.sql
    - mysql < sql/newQueryForceIndex.sql
    - mysql < sql/drop.sql
